/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LameloStats } from "./LameloStats";

export { LameloStats__factory } from "./factories/LameloStats__factory";
