/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface LameloStatsInterface extends ethers.utils.Interface {
  functions: {
    "IsGameOver(uint256)": FunctionFragment;
    "fulfill(bytes32,bytes)": FunctionFragment;
    "getHomeOrAway(uint256)": FunctionFragment;
    "getStats(uint256)": FunctionFragment;
    "statsCount()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "IsGameOver",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfill",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHomeOrAway",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "statsCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IsGameOver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fulfill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHomeOrAway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "statsCount", data: BytesLike): Result;

  events: {};
}

export class LameloStats extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LameloStatsInterface;

  functions: {
    IsGameOver(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getHomeOrAway(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStats(_id: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    statsCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  IsGameOver(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  fulfill(
    _requestId: BytesLike,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getHomeOrAway(_id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getStats(_id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  statsCount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    IsGameOver(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getHomeOrAway(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getStats(_id: BigNumberish, overrides?: CallOverrides): Promise<string>;

    statsCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    IsGameOver(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getHomeOrAway(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStats(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    statsCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    IsGameOver(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fulfill(
      _requestId: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getHomeOrAway(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStats(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    statsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
